const tempData = {
  firstName: "Rony",
  lastName: "Joseph",
  trackerCards: [
    {
      key: "Income",
      amount: "5000.00",
    },
    {
      key: "Expenses",
      amount: "2500.00",
    },
    {
      key: "Investments",
      amount: "2500.00",
    },
  ],
  expenditureData: [
    {
      date: new Date("2022-01-01").getTime(),
      business: "Company A",
      tags: "Groceries",
      amount: 50,
    },
    {
      date: new Date("2022-01-02").getTime(),
      business: "Company B",
      tags: "Utilities",
      amount: 100,
    },
    {
      date: new Date("2022-01-03").getTime(),
      business: "Person A",
      tags: "Food",
      amount: 30,
    },
    {
      date: new Date("2022-01-04").getTime(),
      business: "Company C",
      tags: "Technology",
      amount: 150,
    },
    {
      date: new Date("2022-01-05").getTime(),
      business: "Person B",
      tags: "Gifts",
      amount: 80,
    },
    {
      date: new Date("2022-01-06").getTime(),
      business: "Company A",
      tags: "Groceries",
      amount: 70,
    },
    {
      date: new Date("2022-01-07").getTime(),
      business: "Person C",
      tags: "Food",
      amount: 40,
    },
    {
      date: new Date("2022-01-08").getTime(),
      business: "Company B",
      tags: "Utilities",
      amount: 120,
    },
    {
      date: new Date("2022-01-09").getTime(),
      business: "Person A",
      tags: "Food",
      amount: 60,
    },
    {
      date: new Date("2022-01-10").getTime(),
      business: "Company C",
      tags: "Technology",
      amount: 200,
    },
    {
      date: new Date("2022-01-11").getTime(),
      business: "Person B",
      tags: "Gifts",
      amount: 25,
    },
    {
      date: new Date("2022-01-12").getTime(),
      business: "Company A",
      tags: "Groceries",
      amount: 90,
    },
    {
      date: new Date("2022-01-13").getTime(),
      business: "Person C",
      tags: "Food",
      amount: 35,
    },
    {
      date: new Date("2022-01-13").getTime(),
      business: "Company D",
      tags: "Clothing",
      amount: 65,
    },
    {
      date: new Date("2022-01-13").getTime(),
      business: "Person E",
      tags: "Entertainment",
      amount: 40,
    },
    {
      date: new Date("2022-01-14").getTime(),
      business: "Company B",
      tags: "Utilities",
      amount: 80,
    },
    {
      date: new Date("2022-01-15").getTime(),
      business: "Person A",
      tags: "Gifts",
      amount: 50,
    },
    {
      date: new Date("2022-01-15").getTime(),
      business: "Company D",
      tags: "Technology",
      amount: 90,
    },
    {
      date: new Date("2022-01-15").getTime(),
      business: "Person E",
      tags: "Dining",
      amount: 35,
    },
    {
      date: new Date("2022-01-16").getTime(),
      business: "Company C",
      tags: "Technology",
      amount: 110,
    },
    {
      date: new Date("2022-01-17").getTime(),
      business: "Person B",
      tags: "Food",
      amount: 45,
    },
    {
      date: new Date("2022-01-17").getTime(),
      business: "Company D",
      tags: "Furniture",
      amount: 120,
    },
    {
      date: new Date("2022-01-17").getTime(),
      business: "Person E",
      tags: "Gifts",
      amount: 60,
    },
    {
      date: new Date("2022-01-18").getTime(),
      business: "Company A",
      tags: "Groceries",
      amount: 75,
    },
    {
      date: new Date("2022-01-19").getTime(),
      business: "Person C",
      tags: "Gifts",
      amount: 130,
    },
    {
      date: new Date("2022-01-20").getTime(),
      business: "Company B",
      tags: "Utilities",
      amount: 180,
    },
    {
      date: new Date("2022-01-21").getTime(),
      business: "Person A",
      tags: "Food",
      amount: 40,
    },
    {
      date: new Date("2022-01-22").getTime(),
      business: "Company C",
      tags: "Technology",
      amount: 65,
    },
    {
      date: new Date("2022-01-23").getTime(),
      business: "Person B",
      tags: "Gifts",
      amount: 55,
    },
    {
      date: new Date("2022-01-24").getTime(),
      business: "Company A",
      tags: "Groceries",
      amount: 95,
    },
    {
      date: new Date("2022-01-25").getTime(),
      business: "Person C",
      tags: "Technology",
      amount: 120,
    },
    {
      date: new Date("2022-01-26").getTime(),
      business: "Company B",
      tags: "Utilities",
      amount: 70,
    },
    {
      date: new Date("2022-01-27").getTime(),
      business: "Person A",
      tags: "Gifts",
      amount: 85,
    },
    {
      date: new Date("2022-01-28").getTime(),
      business: "Company C",
      tags: "Technology",
      amount: 55,
    },
    {
      date: new Date("2022-01-29").getTime(),
      business: "Person B",
      tags: "Food",
      amount: 90,
    },
    {
      date: new Date("2022-01-30").getTime(),
      business: "Company A",
      tags: "Groceries",
      amount: 40,
    },
    {
      date: new Date("2022-01-31").getTime(),
      business: "Person C",
      tags: "Entertainment",
      amount: 75,
    },
    {
      date: new Date("2022-02-01").getTime(),
      business: "Company B",
      tags: "Healthcare",
      amount: 110,
    },
    {
      date: new Date("2022-02-02").getTime(),
      business: "Person D",
      tags: "Education",
      amount: 95,
    },
    {
      date: new Date("2022-02-03").getTime(),
      business: "Company A",
      tags: "Furniture",
      amount: 120,
    },
    {
      date: new Date("2022-02-13").getTime(),
      business: "Person E",
      tags: "Dining",
      amount: 45,
    },
    {
      date: new Date("2022-02-13").getTime(),
      business: "Company F",
      tags: "Travel",
      amount: 100,
    },
    {
      date: new Date("2022-02-15").getTime(),
      business: "Person B",
      tags: "Technology",
      amount: 80,
    },
    {
      date: new Date("2022-02-15").getTime(),
      business: "Company G",
      tags: "Groceries",
      amount: 60,
    },
    {
      date: new Date("2022-02-17").getTime(),
      business: "Person C",
      tags: "Food",
      amount: 55,
    },
    {
      date: new Date("2022-02-17").getTime(),
      business: "Company H",
      tags: "Gifts",
      amount: 120,
    },
  ],
};

export default tempData;
